In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import sklearn
%matplotlib inline 

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
titanic = pd.read_csv("E:/UpX/Data Analytics with Python/EDA/notebook/titanic.csv")
titanic.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [5]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [8]:
import pandas_profiling
report = pandas_profiling.ProfileReport(titanic)
report.to_file("titanic_data.html")

In [6]:
pd.isnull(titanic).sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
by_gender_class = titanic.groupby(['Sex','Pclass'])
def imp_median(series):
    return series.fillna(series.median())
titanic.Age = by_gender_class['Age'].transform(imp_median)
titanic.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male  25.0      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [8]:
pd.isnull(titanic).sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
titanic['Embarked'].fillna(str(titanic['Embarked'].mode().values[0]),inplace=True)
pd.isnull(titanic).sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
titanic.Sex = le.fit_transform(titanic.Sex)
titanic.Embarked = le.fit_transform(titanic.Embarked)

In [13]:
titanic.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   
5                                   Moran, Mr. James    1  25.0      0      0   
6                            McCarthy, Mr. Timothy J    1  54.0      0      0   
7                     Palsson, Master. Gosta Leonard    1   2.0      3      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    0  27.0      0      2   
9                Nasser, Mrs. Nicholas (Adele Achem)    0  14.0      1      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2  
5            330877   8.4583   NaN         1  
6             17463  51.8625   E46         2  
7            349909  21.0750   NaN         2  
8            347742  11.1333   NaN         2  
9            237736  30.0708   NaN         0

In [14]:
X = titanic[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
y = titanic['Survived']

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,classification_report

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 42, stratify = y)

X_train.shape
y_train.shape
X_test.shape
y_test.shape

(623, 7)

(623,)

(268, 7)

(268,)

In [59]:
# Use a function for model-evaluation 
def model_evaluation(model):
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)

    if model == Lin_Reg:
        model_name = "Linear Regression"
        y_pred = np.round(abs(y_pred),0)
    elif model == Log_Reg:
        model_name = "Logistic Regression"
    elif model == Deci_Tree:
        model_name = "Decision Tree Classification"
    else:
        model_name = "Random Forest Classification"
    
    print(y_pred)
     
    acc = accuracy_score(y_test, y_pred)
       
    cm = confusion_matrix(y_test, y_pred)
        
    cl_report = classification_report(y_test,y_pred)
    print("Confusion Matrix for "  + model_name + " :")  
    print(cm)
    print("Classification Report "  + model_name + " :") 
    print(cl_report)
    print("Accuracy Score for " + model_name + " :")   
    print(acc)
    return acc

models_dict = {}    # defined a dictionary for all storing the scores of all models 


In [60]:
# 1. Liner Regression model

from sklearn.linear_model import LinearRegression
Lin_Reg = LinearRegression()

LinReg = model_evaluation(Lin_Reg)

models_dict['LinReg'] = {'model':"Linear Regression",
                         'score':LinReg}

[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0.
 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1.
 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 1.
 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 1. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.
 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0.
 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1.
 0. 0. 0. 1.]
Confusion Matrix for Linear Regression :
[[140  25]
 [ 28  75]]
Classification Report Linear Regression :
             precision    recall  f1-score   support

          0       0.83 

In [61]:
#2. Logistic Regression

from sklearn.linear_model import LogisticRegression
Log_Reg = LogisticRegression()

LogReg = model_evaluation(Log_Reg)
models_dict['LogReg'] = {'model':"Logistic Regression",
                         'score':LogReg}

[0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 1 0 1 1 1 0
 0 0 0 0 1 0 1 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1
 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 1 0 1 0 0
 0 0 1 0 0 0 1 1 1 0 1 0 0 1 1 0 0 1 0 1 1 1 0 1 1 0 1 0 1 0 1 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1 0 1 0 0 0
 1 0 0 1 0 0 0 1 1 0 1 1 0 0 0 1 1 0 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0
 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 1 1 0 1 0
 1 1 0 0 1 0 0 0 1]
Confusion Matrix for Logistic Regression :
[[142  23]
 [ 31  72]]
Classification Report Logistic Regression :
             precision    recall  f1-score   support

          0       0.82      0.86      0.84       165
          1       0.76      0.70      0.73       103

avg / total       0.80      0.80      0.80       268

Accuracy Score for Logistic Regression :
0.7985074626865671


In [62]:
#3. DecisionTree Classifier
from sklearn.tree import DecisionTreeClassifier
Deci_Tree = DecisionTreeClassifier(criterion='entropy', random_state=0)

DeciTree = model_evaluation(Deci_Tree)
models_dict['DeciTree'] = {'model':"Decision Tree Classification",
                         'score':DeciTree}

[0 0 0 0 0 0 0 1 0 1 1 1 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 1 1 1 0 1 1 0 0
 0 0 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1
 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 1 1 0 1 0 1 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 0
 1 0 0 0 1 0 1 0 1 0 0 1 0 0 1 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0
 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 1 0 1 1 0
 1 0 1 0 0 0 0 0 1]
Confusion Matrix for Decision Tree Classification :
[[137  28]
 [ 33  70]]
Classification Report Decision Tree Classification :
             precision    recall  f1-score   support

          0       0.81      0.83      0.82       165
          1       0.71      0.68      0.70       103

avg / total       0.77      0.77      0.77       268

Accuracy Score for Decision Tree Classification :
0.7723880597014925


In [63]:
#4 RandomForest Classifier

from sklearn.ensemble import RandomForestClassifier
Ran_Forest = RandomForestClassifier(n_estimators = 10,criterion = 'entropy', random_state= 0)

RandFor = model_evaluation(Ran_Forest)
models_dict['RandFor'] = {'model':"Random Forest Classification",
                          'score':RandFor}

[0 0 0 0 0 0 0 1 0 1 1 1 0 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 1 1 1 0 1 1 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 1
 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 0 0 0 1 1
 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 1 1 0 0
 1 0 0 1 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0
 0 0 1 1 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 1 0 1 0
 0 0 1 0 1 0 0 0 1]
Confusion Matrix for Random Forest Classification :
[[139  26]
 [ 39  64]]
Classification Report Random Forest Classification :
             precision    recall  f1-score   support

          0       0.78      0.84      0.81       165
          1       0.71      0.62      0.66       103

avg / total       0.75      0.76      0.75       268

Accuracy Score for Random Forest Classification :
0.7574626865671642


In [64]:
models_dict

{'DeciTree': {'model': 'Decision Tree Classification',
  'score': 0.7723880597014925},
 'LinReg': {'model': 'Linear Regression', 'score': 0.8022388059701493},
 'LogReg': {'model': 'Logistic Regression', 'score': 0.7985074626865671},
 'RandFor': {'model': 'Random Forest Classification',
  'score': 0.7574626865671642}}